name: storyapp
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flex_color_scheme: ^7.3.1
  provider: ^6.1.2
  shared_preferences: ^2.2.3
  http: ^1.2.1
  google_fonts: ^6.2.1
  camera: ^0.11.0+1
  image_picker: ^1.1.2
  text_area: ^0.0.3
  image_picker_widget: ^2.4.1
  image: ^4.2.0
  json_annotation: ^4.9.0
  google_maps_flutter: ^2.7.0
  google_maps_flutter_web: ^0.5.8
  geocoding: ^3.0.0
  location: ^6.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  build_runner: ^2.4.11
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true